// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {time} from '../models';

export function CreateTask(arg1:string,arg2:string,arg3:data.TaskStatus,arg4:time.Time):Promise<data.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTask(arg1:string):Promise<data.Task>;

export function GetTasks(arg1:string,arg2:string):Promise<Array<data.Task>>;

export function UpdateTask(arg1:string,arg2:any,arg3:any,arg4:data.TaskStatus,arg5:time.Time):Promise<data.Task>;
